title: 4SpecID
description: official website
show_downloads: false
google_analytics: UA-131162060-2
theme: jekyll-theme-hacker
markdown: kramdown
github:
  repository_url: https://github.com/econdesousa/
  

#sidebar:
#  title: "4SpecID"
#  image: "https://4SpecID.github.io/assets/Images/main_icon.png"
#  image_alt: "4SpecID logo"
#  text: home <a href="https://4SpecID.github.io">here</a>!
  